"""Constantes de estilo para la memoria Word (formato de referencia uniforme)."""

FONT = "Arial Narrow"
UNIFORM_FONT_SIZE_PT = 11
COVER_TITLE_FONT_SIZE_PT = 22
TEXT_COLOR = "000000"
NAVY = "173746"
TEAL = "155E75"
LIGHT = "F5F7F8"
GRAY = "61737D"
RULE = "B7C6CC"
GREEN = "2E6B52"
RED = "8D3D32"
NORMAL_MARGIN_MM = 25.4
MAX_CONTENT_WIDTH_MM = 158.0

HEADER_TEXT = "MEMORIA DE CÁLCULO · SOCAVACIÓN"
FOOTER_TEXT = "ANÁLISIS DE SOCAVACIÓN  ·  "
FILENAME_PREFIX = "MEMORIA_CALCULO_SOCAVACION"
